### ISSUE TITLE
RegisterArea Product/{controller}/{action}/{id} incomplete?

### ISSUE THREAD

**Issue by Carlos-Mosquera** [trailmax/ClaimsAuthorisation#1]
Hi, 

When navigate Product and ProductType autorized views, it produce an error when try to select any of top navigation links except Home link.

And not work if removing Product word in registration.

Do I missing somethig?

**Comment by trailmax** [comment]
You need to specify `Area=""` in the links, just like here: http://stackoverflow.com/a/31391435/809357, but in Html.ActionLink
