### ISSUE TITLE
Doesn't work with Safari with many roles/claims

### ISSUE THREAD

**Issue by TDK1964** [trailmax/ClaimsAuthorisation#4]
The chunked cookie is incomplete. Only 1 of the expected 2 chunks were found, totalling 4056 characters. A client size limit may have been exceeded.

**Comment by trailmax** [comment]
Nowhere this codebase does cookie chunking. This is a job of Owin.Cookie - try updating all Owin.* packages to latest version and if the problem persists, raise a ticket in the corresponding project.

**Comment by TDK1964** [comment]
That still doesn't negate the fact that this doesn't work will all browsers?

**Comment by trailmax** [comment]
I have no way of confirming, so can't deny it.
